-- --------------------------------------------------------
-- Host:                         127.0.0.1
-- Server version:               10.1.16-MariaDB - mariadb.org binary distribution
-- Server OS:                    Win32
-- HeidiSQL Version:             9.3.0.4984
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- Dumping database structure for timf
DROP DATABASE IF EXISTS `timf`;
CREATE DATABASE IF NOT EXISTS `timf` /*!40100 DEFAULT CHARACTER SET latin1 */;
USE `timf`;


-- Dumping structure for table timf.members
DROP TABLE IF EXISTS `members`;
CREATE TABLE IF NOT EXISTS `members` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `grouppresident` int(11) DEFAULT '0',
  `fieldofficer` int(11) DEFAULT '0',
  `supervisor` int(11) DEFAULT '0',
  `manager` int(11) DEFAULT '0',
  `finalapproved` int(11) DEFAULT '0',
  `remarks` varchar(50) DEFAULT NULL,
  `ZoneId` int(11) DEFAULT '0',
  `AreaId` int(11) DEFAULT '0',
  `BranchId` int(11) DEFAULT '0',
  `name` varchar(500) DEFAULT NULL,
  `MemberImage` varchar(100) DEFAULT NULL,
  `FatherImage` varchar(100) DEFAULT NULL,
  `MotherImage` varchar(100) DEFAULT NULL,
  `Nid` varchar(100) DEFAULT NULL,
  `NameTitle` varchar(100) DEFAULT NULL,
  `FirstName` varchar(100) DEFAULT NULL,
  `LastName` varchar(100) DEFAULT NULL,
  `FamilyName` varchar(100) DEFAULT NULL,
  `FullNameBangla` varchar(100) DEFAULT NULL,
  `Gender` varchar(100) DEFAULT NULL,
  `Age` varchar(100) DEFAULT NULL,
  `Education` varchar(100) DEFAULT NULL,
  `PassingYear` varchar(100) DEFAULT NULL,
  `SpouseProfession` varchar(100) DEFAULT NULL,
  `SpouseOtherProfession` varchar(100) DEFAULT NULL,
  `SpouseMobileNo` varchar(100) DEFAULT NULL,
  `MaritalStatus` varchar(100) DEFAULT NULL,
  `Mobile` varchar(100) DEFAULT NULL,
  `Email` varchar(100) DEFAULT NULL,
  `PoliticalStatus` varchar(100) DEFAULT NULL,
  `Distance` varchar(100) DEFAULT NULL,
  `WifeNameTitle` varchar(100) DEFAULT NULL,
  `WifeFirstName` varchar(100) DEFAULT NULL,
  `WifeLastName` varchar(100) DEFAULT NULL,
  `WifeFamilyName` varchar(100) DEFAULT NULL,
  `WifeAge` varchar(100) DEFAULT NULL,
  `WifeMobileNo` varchar(100) DEFAULT NULL,
  `WifeProfession` varchar(100) DEFAULT NULL,
  `WifeOtherProfession` varchar(100) DEFAULT NULL,
  `FatherOrHasbandNAmeTitle` varchar(100) DEFAULT NULL,
  `FatherOrHasbandFirstName` varchar(100) DEFAULT NULL,
  `FatherOrHasbandLastName` varchar(100) DEFAULT NULL,
  `FatherOrHasbandFamilyName` varchar(100) DEFAULT NULL,
  `FatherOrHasbandAge` varchar(100) DEFAULT NULL,
  `FatherProfession` varchar(100) DEFAULT NULL,
  `FatherMobileNo` varchar(100) DEFAULT NULL,
  `MatherNameTitle` varchar(100) DEFAULT NULL,
  `MotherFirstName` varchar(100) DEFAULT NULL,
  `MotherLastName` varchar(100) DEFAULT NULL,
  `MotherFamilyName` varchar(100) DEFAULT NULL,
  `MotherAge` varchar(100) DEFAULT NULL,
  `MotherProfession` varchar(100) DEFAULT NULL,
  `MotherMobileNo` varchar(100) DEFAULT NULL,
  `PresentCountry` varchar(100) DEFAULT NULL,
  `PresentDivision` varchar(100) DEFAULT NULL,
  `PresentDistrict` varchar(100) DEFAULT NULL,
  `PresentThana` varchar(100) DEFAULT NULL,
  `PresentUnion` varchar(100) DEFAULT NULL,
  `PresentPostOffice` varchar(100) DEFAULT NULL,
  `PresentWord` varchar(100) DEFAULT NULL,
  `PresentVillage` varchar(100) DEFAULT NULL,
  `PresentRoadNo` varchar(100) DEFAULT NULL,
  `PermanentCountry` varchar(100) DEFAULT NULL,
  `PermanentDivision` varchar(100) DEFAULT NULL,
  `PermanentDistrict` varchar(100) DEFAULT NULL,
  `PermanentThana` varchar(100) DEFAULT NULL,
  `PermanentUnion` varchar(100) DEFAULT NULL,
  `PermanentPostOffice` varchar(100) DEFAULT NULL,
  `PermanentWord` varchar(100) DEFAULT NULL,
  `PermanentVillage` varchar(100) DEFAULT NULL,
  `PermanentRoadNo` varchar(100) DEFAULT NULL,
  `CurrentProfession` varchar(100) DEFAULT NULL,
  `PreviousProfession` varchar(100) DEFAULT NULL,
  `DurationOfPreviousProfession` varchar(100) DEFAULT NULL,
  `EarningAssetsByBusinessOrJob` varchar(100) DEFAULT NULL,
  `EarningSourceWithoutBusiness` varchar(100) DEFAULT NULL,
  `BusinessType1` varchar(100) DEFAULT NULL,
  `BusinessFuturePlan` varchar(100) DEFAULT NULL,
  `FamilyMember` varchar(100) DEFAULT NULL,
  `EarningMale` varchar(100) DEFAULT NULL,
  `EarningFemale` varchar(100) DEFAULT NULL,
  `EarningPerson` varchar(100) DEFAULT NULL,
  `MaleMember` varchar(100) DEFAULT NULL,
  `FemaleMember` varchar(100) DEFAULT NULL,
  `SickDescriptionOfFamilyMember` varchar(100) DEFAULT NULL,
  `CaseDescriptionOfFamilyMember` varchar(100) DEFAULT NULL,
  `IfAnyMemberInAbroad` varchar(100) DEFAULT NULL,
  `FamilyType` varchar(100) DEFAULT NULL,
  `CultiviableLand` varchar(100) DEFAULT NULL,
  `NonCultivableLand` varchar(100) DEFAULT NULL,
  `Pond` varchar(100) DEFAULT NULL,
  `House` varchar(100) DEFAULT NULL,
  `TotalLand` varchar(100) DEFAULT NULL,
  `TinMadeHouse` varchar(100) DEFAULT NULL,
  `StrawMadeHouse` varchar(100) DEFAULT NULL,
  `BrickMadeHouse` varchar(100) DEFAULT NULL,
  `AgriculturalEarning` varchar(100) DEFAULT NULL,
  `NonAgriculturalEarning` varchar(100) DEFAULT NULL,
  `TotalEarning` varchar(100) DEFAULT NULL,
  `TotalExpenditure` varchar(100) DEFAULT NULL,
  `NetBalance` varchar(100) DEFAULT NULL,
  `ReceivedAmount` varchar(100) DEFAULT NULL,
  `PaidAmount` varchar(100) DEFAULT NULL,
  `RemainingAmountToPay` varchar(100) DEFAULT NULL,
  `FinancierCompany` varchar(100) DEFAULT NULL,
  `LoaningYear` varchar(100) DEFAULT NULL,
  `LastReceivedDate` varchar(100) DEFAULT NULL,
  `RepaymentType` varchar(100) DEFAULT NULL,
  `IsHeSheWillingToTakeLoan` varchar(100) DEFAULT NULL,
  `InvestmentSector` varchar(100) DEFAULT NULL,
  `Amount` varchar(100) DEFAULT NULL,
  `Comment1` varchar(100) DEFAULT NULL,
  `Comment2` varchar(100) DEFAULT NULL,
  `FatherNid` varchar(100) DEFAULT NULL,
  `MotherNid` varchar(100) DEFAULT NULL,
  `AccommodationLength` varchar(100) DEFAULT NULL,
  `BusinessName` varchar(100) DEFAULT NULL,
  `BusinessNature` varchar(100) DEFAULT NULL,
  `BusinessExperience` varchar(100) DEFAULT NULL,
  `BusinessCenterAddress` varchar(100) DEFAULT NULL,
  `BusinessStartDate` varchar(100) DEFAULT NULL,
  `Accommodation` varchar(100) DEFAULT NULL,
  `AccommodationWidth` varchar(100) DEFAULT NULL,
  `BusinessPlaceStatus` varchar(100) DEFAULT NULL,
  `Direction` varchar(100) DEFAULT NULL,
  `TradeLicenceNo` varchar(100) DEFAULT NULL,
  `LicenceIssuingAuthority` varchar(100) DEFAULT NULL,
  `InvestedCapital` varchar(100) DEFAULT NULL,
  `MonthlyAvarageSale` varchar(100) DEFAULT NULL,
  `BankContribution` varchar(100) DEFAULT NULL,
  `NgoContribution` varchar(100) DEFAULT NULL,
  `SelfContribution` varchar(100) DEFAULT NULL,
  `BorrowMoney` varchar(100) DEFAULT NULL,
  `MonthlyEarningFromBusiness` varchar(100) DEFAULT NULL,
  `MonthlyExpenditureFromBusiness` varchar(100) DEFAULT NULL,
  `SurplusMoney` varchar(100) DEFAULT NULL,
  `IncomeFromOthersSources` varchar(100) DEFAULT NULL,
  `OtherSources` varchar(100) DEFAULT NULL,
  `MonthlyExpenditureFromOtherSources` varchar(100) DEFAULT NULL,
  `MonthlySurplus` varchar(100) DEFAULT NULL,
  `MonthlyTotalSurplus` varchar(100) DEFAULT NULL,
  `BusinessType` varchar(100) DEFAULT NULL,
  `OwnershipType` varchar(100) DEFAULT NULL,
  `FirstHalfStart` varchar(100) DEFAULT NULL,
  `FirstHalfEnd` varchar(100) DEFAULT NULL,
  `SecondHalfStart` varchar(100) DEFAULT NULL,
  `SecondHalfEnd` varchar(100) DEFAULT NULL,
  `TotalTime` varchar(100) DEFAULT NULL,
  `OrgOPeningTime` varchar(100) DEFAULT NULL,
  `OrgClosingTime` varchar(100) DEFAULT NULL,
  `ClosingIntervalStart` varchar(100) DEFAULT NULL,
  `ClosingIntervalClose` varchar(100) DEFAULT NULL,
  `WeekEnd` varchar(100) DEFAULT NULL,
  `OrgPermanentEmployee` varchar(100) DEFAULT NULL,
  `LoanAccount` varchar(100) DEFAULT NULL,
  `SavingAccount` varchar(100) DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=19 DEFAULT CHARSET=utf8;

-- Dumping data for table timf.members: ~14 rows (approximately)
DELETE FROM `members`;
/*!40000 ALTER TABLE `members` DISABLE KEYS */;
INSERT INTO `members` (`id`, `grouppresident`, `fieldofficer`, `supervisor`, `manager`, `finalapproved`, `remarks`, `ZoneId`, `AreaId`, `BranchId`, `name`, `MemberImage`, `FatherImage`, `MotherImage`, `Nid`, `NameTitle`, `FirstName`, `LastName`, `FamilyName`, `FullNameBangla`, `Gender`, `Age`, `Education`, `PassingYear`, `SpouseProfession`, `SpouseOtherProfession`, `SpouseMobileNo`, `MaritalStatus`, `Mobile`, `Email`, `PoliticalStatus`, `Distance`, `WifeNameTitle`, `WifeFirstName`, `WifeLastName`, `WifeFamilyName`, `WifeAge`, `WifeMobileNo`, `WifeProfession`, `WifeOtherProfession`, `FatherOrHasbandNAmeTitle`, `FatherOrHasbandFirstName`, `FatherOrHasbandLastName`, `FatherOrHasbandFamilyName`, `FatherOrHasbandAge`, `FatherProfession`, `FatherMobileNo`, `MatherNameTitle`, `MotherFirstName`, `MotherLastName`, `MotherFamilyName`, `MotherAge`, `MotherProfession`, `MotherMobileNo`, `PresentCountry`, `PresentDivision`, `PresentDistrict`, `PresentThana`, `PresentUnion`, `PresentPostOffice`, `PresentWord`, `PresentVillage`, `PresentRoadNo`, `PermanentCountry`, `PermanentDivision`, `PermanentDistrict`, `PermanentThana`, `PermanentUnion`, `PermanentPostOffice`, `PermanentWord`, `PermanentVillage`, `PermanentRoadNo`, `CurrentProfession`, `PreviousProfession`, `DurationOfPreviousProfession`, `EarningAssetsByBusinessOrJob`, `EarningSourceWithoutBusiness`, `BusinessType1`, `BusinessFuturePlan`, `FamilyMember`, `EarningMale`, `EarningFemale`, `EarningPerson`, `MaleMember`, `FemaleMember`, `SickDescriptionOfFamilyMember`, `CaseDescriptionOfFamilyMember`, `IfAnyMemberInAbroad`, `FamilyType`, `CultiviableLand`, `NonCultivableLand`, `Pond`, `House`, `TotalLand`, `TinMadeHouse`, `StrawMadeHouse`, `BrickMadeHouse`, `AgriculturalEarning`, `NonAgriculturalEarning`, `TotalEarning`, `TotalExpenditure`, `NetBalance`, `ReceivedAmount`, `PaidAmount`, `RemainingAmountToPay`, `FinancierCompany`, `LoaningYear`, `LastReceivedDate`, `RepaymentType`, `IsHeSheWillingToTakeLoan`, `InvestmentSector`, `Amount`, `Comment1`, `Comment2`, `FatherNid`, `MotherNid`, `AccommodationLength`, `BusinessName`, `BusinessNature`, `BusinessExperience`, `BusinessCenterAddress`, `BusinessStartDate`, `Accommodation`, `AccommodationWidth`, `BusinessPlaceStatus`, `Direction`, `TradeLicenceNo`, `LicenceIssuingAuthority`, `InvestedCapital`, `MonthlyAvarageSale`, `BankContribution`, `NgoContribution`, `SelfContribution`, `BorrowMoney`, `MonthlyEarningFromBusiness`, `MonthlyExpenditureFromBusiness`, `SurplusMoney`, `IncomeFromOthersSources`, `OtherSources`, `MonthlyExpenditureFromOtherSources`, `MonthlySurplus`, `MonthlyTotalSurplus`, `BusinessType`, `OwnershipType`, `FirstHalfStart`, `FirstHalfEnd`, `SecondHalfStart`, `SecondHalfEnd`, `TotalTime`, `OrgOPeningTime`, `OrgClosingTime`, `ClosingIntervalStart`, `ClosingIntervalClose`, `WeekEnd`, `OrgPermanentEmployee`, `LoanAccount`, `SavingAccount`, `created_at`, `updated_at`) VALUES
	(11, 1, 0, 0, 0, 0, NULL, 1, 1, 1, NULL, '123_12316426698_216526605478018_1313829118_n.png', '123_12316426698_216526605478018_1313829118_n.png', '123_12316426698_216526605478018_1313829118_n.png', '123', '1', '1', '1', '1', '1', '1', '1', '1', '1', 'Agriculture', '', '11', NULL, '1', '', '1', '1', '1', '1', '1', '1', '1', '1', 'Agriculture', '', '1', '1', '1', '1', '1', 'Agriculture', '1', '1', '1', '1', '1', '1', 'Agriculture', '1', '17', '1', '1', '1', '1', '1', '1', '1', '1', '17', '1', '1', '1', '1', '1', '1', '1', '1', '1', 'Agriculture', '', '1', '1', NULL, '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '', '', '', '', '', '', '1', '', '1', '1', '', '1', '', '', '', '', '', '', '', '', '', '', '1', '', '122', '', '1', '1', '', '', '', '', '', '', '', '', '', '1', '1', '123_59904', '123_53758', '2017-02-12 09:01:01', '2017-02-13 06:16:28'),
	(12, 1, 0, 0, 0, 0, NULL, 1, 1, 1, NULL, NULL, NULL, NULL, '123', '1', '1', '1', '1', '', '1', '1', '1', '1', 'Agriculture', '', '', NULL, '', '', '1', '1', '1', '', '', '', '1', '', 'Agriculture', '', '1', '', '', '', '1', 'Agriculture', '', '1', '', '', '', '1', 'Agriculture', '', '1', '1', '1', '1', '1', '1', '1', '', '', '1', '1', '1', '1', '1', '1', '1', '', '', '1', 'Agriculture', '', '', '', NULL, '', '1', '1', '1', '1', '1', '1', '', '', '', '1', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '1', '1', '', '', '', '', '', '', '', '', '', '', '', '', '1', '', '1', '1', '', '1', '', '', '', '', '', '', '', '', '', '', '1', '', '', '', '1', '1', '', '', '', '', '', '', '', '', '', '1', '1', '123_52872', '123_55098', '2017-02-12 09:03:57', '2017-02-13 06:21:27'),
	(13, 1, 0, 0, 0, 0, 'it\'s ok', 1, 1, 1, NULL, NULL, NULL, NULL, '123', '1', 'rockey', 'Ahmed', '1', '1', '1', '1', '1', '1', 'Agriculture', '', '1', NULL, '1', '', '1', '1', '1', '1', '1', '1', '1', '1', 'Agriculture', '1', '1', '1', '1', '1', '1', 'Agriculture', '1', '1', '1', '1', '1', '1', 'Agriculture', '', '1', '1', '1', '1', '1', '1', '1', '', '', '1', '1', '1', '1', '1', '1', '1', '', '', '1', 'Agriculture', '', '', '', NULL, '', '1', '1', '1', '1', '1', '1', '', '', '', '1', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '1', '1', '', '', '', '', '', '', '', '', '', '', '', '', '1', '', '1', '1', '', '1', '', '', '', '', '', '', '', '', '', '', '1', '', '', '', '1', '1', '', '', '', '', '', '', '', '', '', '1', '1', '123_54820', '123_57702', '2017-02-12 09:14:02', '2017-02-13 06:22:33'),
	(14, 0, 0, 0, 0, 0, NULL, 1, 1, 1, NULL, '123_1231.jpg', '123_1233.jpg', '123_12312.jpg', '123', '1', '1', '2', '3', '4', '1', '1', '1', '1', 'Agriculture', NULL, '5', '1', '', '7@gmail.com', '1', '1', '1', '2', '', '', '1', '', 'Agriculture', NULL, '1', '', '', '', '1', 'Agriculture', '', '1', '', '', '', '1', 'Agriculture', '', '1', '1', '1', '1', '1', '1', '1', '', '', '1', '1', '1', '1', '1', '1', '1', '', '', '1', 'Agriculture', '', '', '', NULL, '', '1', '1', '1', '1', '1', '1', '', '', '', '1', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '1', '1', '', '', '', '', '', '', '', '', '', '', '', '', '1', '', '1', '1', '', '1', '', '', '', '', '', '', '', '', '', '', '1', '', '', '', '1', '1', '', '', '', '', '', '', '', '', '', '1', '1', '123_58446', '123_52757', '2017-02-13 03:50:59', '2017-02-13 03:50:59'),
	(15, 0, 0, 0, 0, 0, NULL, 1, 1, 1, NULL, '123_1234.jpg', '123_1235.jpg', '123_12315.jpg', '123', '1', '1', '2', '3', '4', '1', '1', '1', '1', 'Agriculture', NULL, '5', '1', '', '7@gmail.com', '1', '1', '1', '2', '', '', '1', '', 'Agriculture', NULL, '1', '', '', '', '1', 'Agriculture', '', '1', '', '', '', '1', 'Agriculture', '', '1', '1', '1', '1', '1', '1', '1', '', '', '1', '1', '1', '1', '1', '1', '1', '', '', '1', 'Agriculture', '', '', '', NULL, '', '1', '1', '1', '1', '1', '1', '', '', '', '1', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '1', '1', '', '', '', '', '', '', '', '', '', '', '', '', '1', '', '1', '1', '', '1', '', '', '', '', '', '', '', '', '', '', '1', '', '', '', '1', '1', '', '', '', '', '', '', '', '', '', '1', '1', '123_58554', '123_57848', '2017-02-13 03:52:58', '2017-02-13 03:52:58'),
	(16, 0, 0, 0, 0, 0, NULL, 1, 1, 1, NULL, NULL, NULL, NULL, '123', '1', '1', '2', '3', '4', '1', '1', '1', '1', 'Agriculture', NULL, '5', '1', '', '7@gmail.com', '1', '1', '1', '2', '', '', '1', '', 'Agriculture', NULL, '1', '', '', '', '1', 'Agriculture', '', '1', '', '', '', '1', 'Agriculture', '', '1', '1', '1', '1', '1', '1', '1', '', '', '1', '1', '1', '1', '1', '1', '1', '', '', '1', 'Agriculture', '', '', '', NULL, '', '1', '1', '1', '1', '1', '1', '', '', '', '1', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '1', '1', '', '', '', '', '', '', '', '', '', '', '', '', '1', '', '1', '1', '', '1', '', '', '', '', '', '', '', '', '', '', '1', '', '', '', '1', '1', '', '', '', '', '', '', '', '', '', '1', '1', '123_54541', '123_57611', '2017-02-13 06:23:22', '2017-02-13 06:23:22'),
	(17, 0, 0, 0, 0, 0, NULL, 1, 1, 1, NULL, NULL, NULL, NULL, '123', '1', '1', '2', '3', '4', '1', '1', '1', '1', 'Agriculture', NULL, '5', '1', '', '7@gmail.com', '1', '1', '1', '2', '', '', '1', '', 'Agriculture', NULL, '1', '', '', '', '1', 'Agriculture', '', '1', '', '', '', '1', 'Agriculture', '', '1', '1', '1', '1', '1', '1', '1', '', '', '1', '1', '1', '1', '1', '1', '1', '', '', '1', 'Agriculture', '', '', '', NULL, '', '1', '1', '1', '1', '1', '1', '', '', '', '1', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '1', '1', '', '', '', '', '', '', '', '', '', '', '', '', '1', '', '1', '1', '', '1', '', '', '', '', '', '', '', '', '', '', '1', '', '', '', '1', '1', '', '', '', '', '', '', '', '', '', '1', '1', '123_57449', '123_51929', '2017-02-13 06:23:27', '2017-02-13 06:23:27'),
	(18, 0, 0, 0, 0, 0, NULL, 1, 1, 1, NULL, NULL, NULL, NULL, '123', '1', '1', '2', '3', '4', '1', '1', '1', '1', 'Agriculture', NULL, '5', '1', '', '7@gmail.com', '1', '1', '1', '2', '', '', '1', '', 'Agriculture', NULL, '1', '', '', '', '1', 'Agriculture', '', '1', '', '', '', '1', 'Agriculture', '', '1', '1', '1', '1', '1', '1', '1', '', '', '1', '1', '1', '1', '1', '1', '1', '', '', '1', 'Agriculture', '', '', '', NULL, '', '1', '1', '1', '1', '1', '1', '', '', '', '1', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '1', '1', '', '', '', '', '', '', '', '', '', '', '', '', '1', '', '1', '1', '', '1', '', '', '', '', '', '', '', '', '', '', '1', '', '', '', '1', '1', '', '', '', '', '', '', '', '', '', '1', '1', '123_51500', '123_50296', '2017-02-13 06:23:35', '2017-02-13 06:23:35');
/*!40000 ALTER TABLE `members` ENABLE KEYS */;
/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
